config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :kittens
  # Defines the root path route ("/")
  # root "articles#index"
  root "kittens#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  before_action :set_kitten, only: %i[ show edit update destroy ]

  def index
    @kitten = Kitten.all
    respond_to do |format|
      format.html
      format.json { render json: @kitten }
    end
  end

  def show
    
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)

    respond_to do |format|
      if @kitten.save
        format.html { redirect_to kitten_url(@kitten), notice: "Kitten was successfully created." }
        format.json { render json: @kitten }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @kitten.errors, status: :unprocessable_entity }
      end
    end

  end

  def edit

  end

  def update
    respond_to do |format|
      if @kitten.update(kitten_params)
        format.html { redirect_to kitten_url(@kitten), notice: "Kitten was successfully updated." }
        format.json { render :show, status: :ok, location: @kitten }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @kitten.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @kitten.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: "Kitten was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def set_kitten
      @kitten = Kitten.find(params[:id])
    end

    def kitten_params
        params.require(:kitten).permit(:name, :age, :cuteness, :softness)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_with(model: @kitten) do |f| %>
  <%= f.text_field :name, placeholder:"Name Of Your Kitten"%>
  <%= f.number_field :age, placeholder:"Age Of Your Kitten" %>
  <%= f.text_field :cuteness, placeholder:"Your Kittens Cuteness" %>
  <%= f.text_field :softness, placeholder:"Your Kittens Softness" %>
  <%= f.submit "Submit", class:"btn btn-primary" %>
<% end %>

app/views/kittens/edit.html.erb
<%= render 'form', kitten: @kitten %>
<%= button_to "Delete", @kitten, method: :delete , class:"btn btn-danger" %>
<%= link_to "Home", root_path, class:"btn btn-primary" %>

app/views/kittens/index.html.erb
<div class="container-fluid">
  <%= link_to "Create Kitten", new_kitten_path %>
  <% @kitten.each do |k| %>
  <div class="card">
    <div class="card-body">
      <h5 class="card-title"><%= k.name %></h5>
      <p class="card-text">Age: <%= k.age %></p>
      <p class="card-text">Cuteness: <%= k.cuteness %></p>
      <p class="card-text">Softness: <%=k.softness %></p>
    </div>
    <%= link_to "kitten", k, class:"btn btn-primary" %>
    <%= button_to "Delete", k, method: :delete , class:"btn btn-danger" %>
  </div>
  <% end %>
</div>

app/views/kittens/new.html.erb
<%= render 'form' %>

app/views/kittens/show.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title"><%= @kitten.name %></h5>
    <p class="card-text">Age: <%= @kitten.age %></p>
    <p class="card-text">Cuteness: <%= @kitten.cuteness %></p>
    <p class="card-text">Softness: <%= @kitten.softness %></p>
  </div>
</div>
<div class="d-grid gap-2">
    <%= link_to "Edit", edit_kitten_path, class:"btn btn-primary" %>
    <%= button_to "Delete", @kitten, method: :delete , class:"btn btn-danger" %>
    <%= link_to "Home", root_path, class:"btn btn-primary" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-primary global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger global-notification">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>